//! Swift FFI binding — `staticlib` + `cdylib` + `rlib` crate для сборки
//! XCFramework и Swift Package. Реальные FFI типы и функции живут в
//! [`umbrella_ffi`] — этот крейт re-export'ирует публичные Rust-типы и
//! re-export'ирует UniFFI scaffolding symbols из [`umbrella_ffi`].
//!
//! # Сборка
//!
//! Cargo targets:
//!
//! - `staticlib` → `libumbrella_ffi_swift.a` — embed в XCFramework.
//! - `cdylib` → `libumbrella_ffi_swift.dylib` — dev symbol resolution.
//! - `rlib` — требуется чтобы `[[bin]]` `uniffi-bindgen-swift` мог
//!   `use umbrella_ffi_swift;` для re-exports scaffolding.
//!
//! Swift binding генерируется через `cargo run --bin uniffi-bindgen-swift --
//! generate --library <path-to-.a> --language swift --out-dir ...` в
//! `build-xcframework.sh`.
//!
//! Swift FFI binding — `staticlib` + `cdylib` + `rlib` crate for building the
//! XCFramework and Swift Package. Real FFI types and functions live in
//! [`umbrella_ffi`] — this crate re-exports the public Rust types and
//! re-exports UniFFI scaffolding symbols from [`umbrella_ffi`].
//!
//! # Build
//!
//! Cargo targets:
//!
//! - `staticlib` → `libumbrella_ffi_swift.a` — embedded in the XCFramework.
//! - `cdylib` → `libumbrella_ffi_swift.dylib` — dev symbol resolution.
//! - `rlib` — required so the `uniffi-bindgen-swift` `[[bin]]` can
//!   `use umbrella_ffi_swift;` for scaffolding re-exports.
//!
//! The Swift binding is generated via `cargo run --bin uniffi-bindgen-swift
//! -- generate --library <path-to-.a> --language swift --out-dir ...` inside
//! `build-xcframework.sh`.

#![warn(missing_docs)]

pub use umbrella_ffi::*;

/// Маркер сборки — обновляется при мажорном изменении Swift binding surface.
///
/// Build marker — updated on major Swift binding surface changes.
pub const BUILD_MARKER: &str = "umbrella-ffi-swift stage-7.8 xcframework";

// Re-export scaffolding symbols generated by umbrella-ffi. Creating a second
// namespace in this wrapper makes bindgen see metadata items for crate
// `umbrella_ffi` without a matching namespace group.
umbrella_ffi::uniffi_reexport_scaffolding!();
