//! Derive + verify identity fingerprint для DTLS, и вычисление симметричного
//! mutual-binding (UI safety-number звонка).
//!
//! ## Конструкция
//!
//! ```text
//! IdentityDtlsFingerprint::derive(pk, nonce)
//!     = SHA-256("umbrellax-dtls-identity-v1" || pk || nonce)
//!
//! compute_mutual_identity_binding(a, b, nonce)
//!     = SHA-256("umbrellax-dtls-mutual-v1" || min(a, b) || max(a, b) || nonce)
//! ```
//!
//! Session nonce — per-call 16-байтовое random значение (генерируется на стороне
//! signalling / webrtc-rs), не секретное, но уникальное. Предотвращает replay
//! fingerprint'а между сессиями.
//!
//! Lexicographic ordering (`min`/`max`) в mutual-binding гарантирует симметрию:
//! оба клиента получают одинаковое 32-байтовое значение независимо от порядка
//! аргументов — идеально для отображения UI safety-number.
//!
//! Все публичные verify-функции используют `subtle::ConstantTimeEq` —
//! сравнение байт в constant-time, устойчивое к timing-attacks.
//!
//! Derive + verify of the DTLS identity fingerprint, plus the symmetric
//! mutual-binding computation (UI call safety-number).
//!
//! ## Construction
//!
//! ```text
//! IdentityDtlsFingerprint::derive(pk, nonce)
//!     = SHA-256("umbrellax-dtls-identity-v1" || pk || nonce)
//!
//! compute_mutual_identity_binding(a, b, nonce)
//!     = SHA-256("umbrellax-dtls-mutual-v1" || min(a, b) || max(a, b) || nonce)
//! ```
//!
//! `session_nonce` is a per-call 16-byte random value (generated by the
//! signalling layer / webrtc-rs); not secret, but unique. Prevents
//! fingerprint replay across sessions.
//!
//! Lexicographic `min`/`max` in mutual-binding guarantees symmetry: both
//! peers get the same 32-byte value regardless of argument order — ideal
//! for rendering a UI safety-number.
//!
//! Every public verify routine uses `subtle::ConstantTimeEq` —
//! constant-time byte comparison resistant to timing attacks.

use sha2::{Digest, Sha256};
use subtle::ConstantTimeEq;

use crate::error::{CallError, Result};

/// Длина session nonce — 16 байт (128 бит). Генерируется webrtc-rs или
/// signalling-слоем; per-session уникальный, не секретный.
///
/// Session nonce length — 16 bytes (128 bits). Generated by webrtc-rs or
/// the signalling layer; per-session unique, not secret.
pub const SESSION_NONCE_LEN: usize = 16;

/// Длина identity pubkey — 32 байта (Ed25519 compressed).
/// Identity pubkey length — 32 bytes (compressed Ed25519).
pub const IDENTITY_PUBKEY_LEN: usize = 32;

/// Длина fingerprint — 32 байта (SHA-256 output).
/// Fingerprint length — 32 bytes (SHA-256 output).
pub const FINGERPRINT_LEN: usize = 32;

/// Domain separator для identity fingerprint derive.
/// Domain separator for identity fingerprint derive.
const DOMAIN_IDENTITY: &[u8] = b"umbrellax-dtls-identity-v1";

/// Domain separator для mutual identity binding.
/// Domain separator for mutual identity binding.
const DOMAIN_MUTUAL: &[u8] = b"umbrellax-dtls-mutual-v1";

/// Identity-bound DTLS fingerprint. 32 байта `SHA-256`-выхода, встраиваемые
/// в DTLS certificate на стороне `webrtc-rs` в Этапе 7. Реализует
/// `Debug / Clone / Copy / PartialEq / Eq` — сами байты публично не
/// секретные (это хэш pubkey и nonce, не секрета).
///
/// Identity-bound DTLS fingerprint. 32 bytes of `SHA-256` output, embedded
/// in the DTLS certificate by `webrtc-rs` in Stage 7. Derives
/// `Debug / Clone / Copy / PartialEq / Eq` — the bytes are not secret
/// (a hash of a pubkey and a nonce, not a secret).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct IdentityDtlsFingerprint([u8; FINGERPRINT_LEN]);

impl IdentityDtlsFingerprint {
    /// Детерминистический derive:
    /// `SHA-256(DOMAIN_IDENTITY || identity_pubkey || session_nonce)`.
    ///
    /// Session nonce предотвращает replay fingerprint'а между звонками
    /// (один и тот же identity_pubkey даёт разные fingerprint'ы для разных
    /// сессий).
    ///
    /// Deterministic derive:
    /// `SHA-256(DOMAIN_IDENTITY || identity_pubkey || session_nonce)`.
    ///
    /// The session nonce prevents fingerprint replay across calls (the
    /// same `identity_pubkey` produces distinct fingerprints in different
    /// sessions).
    pub fn derive(
        identity_pubkey: &[u8; IDENTITY_PUBKEY_LEN],
        session_nonce: &[u8; SESSION_NONCE_LEN],
    ) -> Self {
        let mut hasher = Sha256::new();
        hasher.update(DOMAIN_IDENTITY);
        hasher.update(identity_pubkey);
        hasher.update(session_nonce);
        let out = hasher.finalize();
        let mut bytes = [0u8; FINGERPRINT_LEN];
        bytes.copy_from_slice(&out);
        Self(bytes)
    }

    /// Constant-time равенство. `true` если fingerprint'ы совпадают.
    /// Устойчиво к timing-attacks (`subtle::ConstantTimeEq`).
    ///
    /// Constant-time equality. `true` if the fingerprints match.
    /// Resistant to timing attacks (`subtle::ConstantTimeEq`).
    pub fn verify_constant_time(&self, other: &Self) -> bool {
        self.0.ct_eq(&other.0).into()
    }

    /// Constant-time verify с конкретной ошибкой при mismatch.
    /// Предпочтительно для API-слоя — сразу даёт `Result`.
    ///
    /// Constant-time verify that returns a specific error on mismatch.
    /// Preferred at API boundaries — yields a `Result` directly.
    pub fn verify_or_err(&self, expected: &Self) -> Result<()> {
        if self.verify_constant_time(expected) {
            Ok(())
        } else {
            Err(CallError::IdentityBindingFailed)
        }
    }

    /// Bytes accessor — для подстановки в DTLS certificate на Этапе 7.
    /// Bytes accessor — used to embed the fingerprint in the DTLS certificate
    /// on Stage 7.
    pub fn as_bytes(&self) -> &[u8; FINGERPRINT_LEN] {
        &self.0
    }
}

/// Симметричный mutual fingerprint — UI safety-number звонка.
/// Оба клиента выводят одинаковое 32-байтовое значение независимо от порядка
/// аргументов. Использует lexicographic ordering (`lo = min(a, b)`,
/// `hi = max(a, b)`) и отдельный `DOMAIN_MUTUAL` domain separator.
///
/// Signal-style safety-number, но **per-call** (через session_nonce) вместо
/// per-identity: каждый звонок — новое значение, не раскрывает identity
/// через long-lived safety-number.
///
/// Symmetric mutual fingerprint — UI safety-number for the call. Both
/// peers derive the same 32-byte value regardless of argument order. Uses
/// lexicographic ordering (`lo = min(a, b)`, `hi = max(a, b)`) and a
/// separate `DOMAIN_MUTUAL` domain separator.
///
/// Signal-style safety-number, but **per-call** (via `session_nonce`)
/// rather than per-identity: every call gets a new value and does not
/// leak identity through a long-lived safety-number.
pub fn compute_mutual_identity_binding(
    local_pubkey: &[u8; IDENTITY_PUBKEY_LEN],
    peer_pubkey: &[u8; IDENTITY_PUBKEY_LEN],
    session_nonce: &[u8; SESSION_NONCE_LEN],
) -> [u8; FINGERPRINT_LEN] {
    let (lo, hi) = if local_pubkey <= peer_pubkey {
        (local_pubkey, peer_pubkey)
    } else {
        (peer_pubkey, local_pubkey)
    };
    let mut hasher = Sha256::new();
    hasher.update(DOMAIN_MUTUAL);
    hasher.update(lo);
    hasher.update(hi);
    hasher.update(session_nonce);
    let out = hasher.finalize();
    let mut bytes = [0u8; FINGERPRINT_LEN];
    bytes.copy_from_slice(&out);
    bytes
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    #[test]
    fn derive_deterministic_same_inputs() {
        let pk = [0xAB; IDENTITY_PUBKEY_LEN];
        let nonce = [0x42; SESSION_NONCE_LEN];
        let fp1 = IdentityDtlsFingerprint::derive(&pk, &nonce);
        let fp2 = IdentityDtlsFingerprint::derive(&pk, &nonce);
        assert_eq!(fp1, fp2);
        assert_eq!(fp1.as_bytes().len(), FINGERPRINT_LEN);
    }

    #[test]
    fn derive_different_pubkey_different_fp() {
        let pk_a = [0xAA; IDENTITY_PUBKEY_LEN];
        let pk_b = [0xBB; IDENTITY_PUBKEY_LEN];
        let nonce = [0x42; SESSION_NONCE_LEN];
        let fp_a = IdentityDtlsFingerprint::derive(&pk_a, &nonce);
        let fp_b = IdentityDtlsFingerprint::derive(&pk_b, &nonce);
        assert_ne!(fp_a, fp_b);
    }

    #[test]
    fn derive_different_nonce_different_fp() {
        let pk = [0xAB; IDENTITY_PUBKEY_LEN];
        let nonce_a = [0x01; SESSION_NONCE_LEN];
        let nonce_b = [0x02; SESSION_NONCE_LEN];
        let fp_a = IdentityDtlsFingerprint::derive(&pk, &nonce_a);
        let fp_b = IdentityDtlsFingerprint::derive(&pk, &nonce_b);
        assert_ne!(fp_a, fp_b);
    }

    #[test]
    fn verify_constant_time_positive() {
        let pk = [0xAB; IDENTITY_PUBKEY_LEN];
        let nonce = [0x42; SESSION_NONCE_LEN];
        let fp = IdentityDtlsFingerprint::derive(&pk, &nonce);
        assert!(fp.verify_constant_time(&fp));
    }

    #[test]
    fn verify_constant_time_negative() {
        let pk_a = [0xAA; IDENTITY_PUBKEY_LEN];
        let pk_b = [0xBB; IDENTITY_PUBKEY_LEN];
        let nonce = [0x42; SESSION_NONCE_LEN];
        let fp_a = IdentityDtlsFingerprint::derive(&pk_a, &nonce);
        let fp_b = IdentityDtlsFingerprint::derive(&pk_b, &nonce);
        assert!(!fp_a.verify_constant_time(&fp_b));
    }

    #[test]
    fn verify_or_err_ok_on_match() {
        let pk = [0xAB; IDENTITY_PUBKEY_LEN];
        let nonce = [0x42; SESSION_NONCE_LEN];
        let fp = IdentityDtlsFingerprint::derive(&pk, &nonce);
        fp.verify_or_err(&fp).unwrap();
    }

    #[test]
    fn verify_or_err_fails_on_mismatch() {
        let pk_a = [0xAA; IDENTITY_PUBKEY_LEN];
        let pk_b = [0xBB; IDENTITY_PUBKEY_LEN];
        let nonce = [0x42; SESSION_NONCE_LEN];
        let fp_a = IdentityDtlsFingerprint::derive(&pk_a, &nonce);
        let fp_b = IdentityDtlsFingerprint::derive(&pk_b, &nonce);
        let err = fp_a.verify_or_err(&fp_b).unwrap_err();
        assert!(matches!(err, CallError::IdentityBindingFailed));
    }

    #[test]
    fn derive_domain_separation_from_mutual() {
        // Domain separation: IdentityDtlsFingerprint::derive и
        // compute_mutual_identity_binding с совпадающими byte-strings на входе
        // должны давать ≠ outputs из-за разных domain separator'ов.
        //
        // Domain separation: IdentityDtlsFingerprint::derive and
        // compute_mutual_identity_binding with matching byte-string inputs
        // must produce distinct outputs thanks to the different domain
        // separators.
        let pk = [0xAB; IDENTITY_PUBKEY_LEN];
        let nonce = [0x42; SESSION_NONCE_LEN];
        let identity_fp = IdentityDtlsFingerprint::derive(&pk, &nonce);
        // mutual с pk=pk даст hash("umbrellax-dtls-mutual-v1" || pk || pk || nonce) —
        // отличные от identity input bytes, но фундаментально отличен domain.
        //
        // mutual with pk=pk hashes "umbrellax-dtls-mutual-v1" || pk || pk || nonce —
        // different input bytes and a different domain.
        let mutual = compute_mutual_identity_binding(&pk, &pk, &nonce);
        assert_ne!(identity_fp.as_bytes(), &mutual);
    }

    #[test]
    fn mutual_binding_symmetric() {
        let pk_a = [0xAA; IDENTITY_PUBKEY_LEN];
        let pk_b = [0xBB; IDENTITY_PUBKEY_LEN];
        let nonce = [0x42; SESSION_NONCE_LEN];
        let from_a = compute_mutual_identity_binding(&pk_a, &pk_b, &nonce);
        let from_b = compute_mutual_identity_binding(&pk_b, &pk_a, &nonce);
        assert_eq!(from_a, from_b);
    }

    #[test]
    fn mutual_binding_different_nonce_different_result() {
        let pk_a = [0xAA; IDENTITY_PUBKEY_LEN];
        let pk_b = [0xBB; IDENTITY_PUBKEY_LEN];
        let nonce_a = [0x01; SESSION_NONCE_LEN];
        let nonce_b = [0x02; SESSION_NONCE_LEN];
        let r_a = compute_mutual_identity_binding(&pk_a, &pk_b, &nonce_a);
        let r_b = compute_mutual_identity_binding(&pk_a, &pk_b, &nonce_b);
        assert_ne!(r_a, r_b);
    }

    #[test]
    fn mutual_binding_identical_pubkeys_valid() {
        // Edge: те же identity (редкий, но возможный случай — звонок с самим собой).
        // Edge: identical identities (rare but possible — self-call scenario).
        let pk = [0xAA; IDENTITY_PUBKEY_LEN];
        let nonce = [0x42; SESSION_NONCE_LEN];
        let r = compute_mutual_identity_binding(&pk, &pk, &nonce);
        assert_eq!(r.len(), FINGERPRINT_LEN);
    }

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(128))]

        #[test]
        fn prop_derive_roundtrip(
            pk in any::<[u8; IDENTITY_PUBKEY_LEN]>(),
            nonce in any::<[u8; SESSION_NONCE_LEN]>(),
        ) {
            let fp1 = IdentityDtlsFingerprint::derive(&pk, &nonce);
            let fp2 = IdentityDtlsFingerprint::derive(&pk, &nonce);
            prop_assert!(fp1.verify_constant_time(&fp2));
        }

        #[test]
        fn prop_mutual_symmetric(
            pk_a in any::<[u8; IDENTITY_PUBKEY_LEN]>(),
            pk_b in any::<[u8; IDENTITY_PUBKEY_LEN]>(),
            nonce in any::<[u8; SESSION_NONCE_LEN]>(),
        ) {
            let from_a = compute_mutual_identity_binding(&pk_a, &pk_b, &nonce);
            let from_b = compute_mutual_identity_binding(&pk_b, &pk_a, &nonce);
            prop_assert_eq!(from_a, from_b);
        }
    }
}
