//! Общие примитивы фасадов. Не `pub use` наружу в `lib.rs` — доступны по
//! пути `umbrella_client::facade::chat_common::*` чтобы не засорять корневой
//! re-export (ADR-006 Вариант C — фасады это точки входа, а не примитивы).
//!
//! `send_mls_text` — shared низкоуровневый helper (MLS AEAD + padding);
//! обёртки в [`CloudChat`]/[`SecretChat`] делают режим-специфичные шаги
//! (Cloud-wrap для Cloud, sealed-sender → blind-postman для Secret).
//! В Блоке 7.2 — stub; реальная реализация — Блок 7.4.
//!
//! Facade-wide primitives. Not re-exported from `lib.rs` — reached via
//! `umbrella_client::facade::chat_common::*`, so the crate root re-exports
//! remain focused on the two facade entry points (ADR-006 Variant C).
//!
//! `send_mls_text` is the shared low-level helper (MLS AEAD + padding); the
//! wrappers in [`CloudChat`]/[`SecretChat`] perform the mode-specific steps
//! (Cloud-wrap for Cloud, sealed-sender → blind-postman for Secret). Stub in
//! Block 7.2; real implementation in Block 7.4.
//!
//! [`CloudChat`]: crate::facade::CloudChat
//! [`SecretChat`]: crate::facade::SecretChat

use std::sync::Arc;

use crate::core::ClientCore;
use crate::error::{ClientError, Result};
use crate::transport::{ClientPayload, ServerPayload};

/// Opaque идентификатор чата. 32 байта; для MLS-групп совпадает с
/// `MLSGroupId`. В Cloud-режиме также является ключом индекса на Почтальоне
/// и OPRF-меткой для contact-discovery.
///
/// Opaque chat identifier. 32 bytes; matches `MLSGroupId` for MLS groups. In
/// Cloud mode it also indexes the Postman mailbox and acts as the OPRF label
/// for contact-discovery.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ChatId(pub [u8; 32]);

/// Идентичность собеседника — public Ed25519 identity key (32 байта).
/// В блоках 7.5/7.6 верифицируется через KT proof + DTLS fingerprint binding.
///
/// Peer identity — public Ed25519 identity key (32 bytes). Verified via KT
/// proof + DTLS fingerprint binding in Blocks 7.5/7.6.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct PeerId(pub [u8; 32]);

impl From<PeerId> for umbrella_calls::PeerId {
    fn from(peer: PeerId) -> Self {
        umbrella_calls::PeerId(peer.0)
    }
}

impl From<umbrella_calls::PeerId> for PeerId {
    fn from(peer: umbrella_calls::PeerId) -> Self {
        PeerId(peer.0)
    }
}

/// Идентификатор сообщения. 16 байт opaque UUID-v4-like; генерируется
/// отправителем, используется для deduplication на Почтальоне.
///
/// Message identifier. 16 bytes opaque UUID-v4-like; generated by the sender,
/// used for deduplication on the Postman.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct MessageId(pub [u8; 16]);

/// Timestamp в миллисекундах Unix epoch. `u64` чтобы покрыть > 500M лет.
///
/// Timestamp in Unix-epoch milliseconds. `u64` for >500M-year horizon.
pub type Timestamp = u64;

/// Общие настройки чата, устанавливаемые при создании.
///
/// Common chat settings set at creation time.
#[derive(Debug, Clone, Default)]
pub struct ChatSettings {
    /// Заголовок — display-only на клиентской стороне. `None` = без title.
    /// Title — display-only on the client side. `None` = no title.
    pub title: Option<String>,

    /// Unix-timestamp создания в миллисекундах.
    /// Creation time in Unix-epoch milliseconds.
    pub created_at_millis: Timestamp,

    /// Опциональный per-чат IANA ciphersuite (RFC 9420 §17.1). `None` →
    /// фасад берёт `ClientCore::default_ciphersuite()` (по умолчанию
    /// `0x0003` classical, а в PQ-режиме `0x004D` X-Wing — устанавливается
    /// через `UmbrellaClient::bootstrap_pq_for_test` под feature `pq`).
    /// `Some(0x0003)` — явный classical, `Some(0x004D)` — явный hybrid PQ
    /// (требует feature `pq`; иначе MLS layer вернёт `MlsError::Capabilities`
    /// при попытке group create — постулат 14, no silent fallback).
    ///
    /// Поле добавлено в Этапе 8 блок 8.8 closing milestone (ADR-011 + design.md
    /// §11.2 «FFI ABI 0.0.11 invariant»). Backwards compat: existing call
    /// sites без этого поля используют `..Default::default()` и получают
    /// `None` → дефолт `ClientCore`.
    ///
    /// Optional per-chat IANA ciphersuite (RFC 9420 §17.1). `None` → the
    /// facade falls back to `ClientCore::default_ciphersuite()` (classical
    /// `0x0003` by default, or `0x004D` X-Wing in PQ mode set up via
    /// `UmbrellaClient::bootstrap_pq_for_test` under feature `pq`).
    /// `Some(0x0003)` is an explicit classical request; `Some(0x004D)` an
    /// explicit hybrid PQ request (requires feature `pq`; otherwise the MLS
    /// layer returns `MlsError::Capabilities` on group create — postulate 14,
    /// no silent fallback).
    ///
    /// Field added in Stage 8 Block 8.8 closing milestone (ADR-011 +
    /// design.md §11.2 «FFI ABI 0.0.11 invariant»). Backwards-compatible:
    /// existing call sites without this field use `..Default::default()` and
    /// receive `None` → fall back to `ClientCore`.
    pub ciphersuite: Option<u16>,
}

/// IANA ID classical Umbrella default ciphersuite
/// (`MLS_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519`, RFC 9420 §17.1).
/// Применяется когда ни `ChatSettings.ciphersuite`, ни bootstrap-режим явно
/// не задают другое значение (т.е. для existing 0.0.11 call sites). Зеркалирует
/// `umbrella_mls::ciphersuite::UMBRELLA_DEFAULT_CIPHERSUITE.raw_id()` без
/// циклической зависимости фасад → MLS на уровне типов (постулат 14:
/// MLS не должен быть compile-time required при `--no-default-features`).
///
/// IANA ID for the classical Umbrella default ciphersuite
/// (`MLS_128_DHKEMX25519_CHACHA20POLY1305_SHA256_Ed25519`, RFC 9420 §17.1).
/// Used when neither `ChatSettings.ciphersuite` nor the bootstrap mode pin a
/// value (i.e. all existing 0.0.11 call sites). Mirrors
/// `umbrella_mls::ciphersuite::UMBRELLA_DEFAULT_CIPHERSUITE.raw_id()` without
/// requiring a type-level dependency from the facade onto MLS for non-MLS
/// crates (postulate 14: MLS should not be compile-time required at
/// `--no-default-features`).
pub const UMBRELLA_CIPHERSUITE_CLASSICAL_DEFAULT: u16 = 0x0003;

/// IANA ID hybrid PQ Umbrella ciphersuite
/// (`MLS_256_XWING_CHACHA20POLY1305_SHA256_Ed25519`, draft-ietf-mls-pq-ciphersuites).
/// Применяется по умолчанию когда клиент bootstrap'нут через
/// `UmbrellaClient::bootstrap_pq_for_test` (feature `pq`).
///
/// IANA ID for the hybrid PQ Umbrella ciphersuite
/// (`MLS_256_XWING_CHACHA20POLY1305_SHA256_Ed25519`, draft-ietf-mls-pq-ciphersuites).
/// Used as the default when the client is bootstrapped via
/// `UmbrellaClient::bootstrap_pq_for_test` (feature `pq`).
#[cfg(feature = "pq")]
pub const UMBRELLA_CIPHERSUITE_PQ_HYBRID: u16 = 0x004D;

/// Расшифрованное сообщение — результат `fetch_inbox`.
///
/// Decrypted message — result of `fetch_inbox`.
#[derive(Clone)]
pub struct DecryptedMessage {
    /// Идентификатор сообщения.
    /// Message identifier.
    pub message_id: MessageId,

    /// Чат, к которому принадлежит сообщение.
    /// Chat this message belongs to.
    pub chat_id: ChatId,

    /// Отправитель — identity pubkey после sealed-sender unwrap.
    /// Sender — identity pubkey after sealed-sender unwrap.
    pub sender: PeerId,

    /// Unix-timestamp (миллисекунды) по часам отправителя.
    /// Sender-clock Unix-timestamp (milliseconds).
    pub timestamp: Timestamp,

    /// Plaintext текста сообщения. В Блоке 7.2 — stub "" для тестов;
    /// реальное plaintext появляется в Блоке 7.4 через MLS decrypt.
    ///
    /// Plaintext message body. Stub "" in Block 7.2; real plaintext emerges
    /// in Block 7.4 via MLS decrypt.
    pub text: String,
}

/// `Debug` скрывает тело сообщения, но оставляет безопасную диагностику.
/// `Debug` redacts the message body while preserving safe diagnostics.
impl core::fmt::Debug for DecryptedMessage {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("DecryptedMessage")
            .field("message_id", &self.message_id)
            .field("chat_id", &self.chat_id)
            .field("sender", &self.sender)
            .field("timestamp", &self.timestamp)
            .field("text_len", &self.text.len())
            .field("text", &"<redacted>")
            .finish()
    }
}

/// Длина hex-encoded `SendMessageAck.msg_id` (`umbrellax.gateway.v1.SendMessageAck`,
/// `rust_1mlrd/proto/umbrellax/gateway/v1/ws.proto:60`): 16 байт opaque
/// id, отдаваемые сервером как 32 lowercase hex symbol строка
/// (`rust_1mlrd/.../transport/protobuf_codec.rs` + контракт §4.1).
///
/// Length of the hex-encoded `SendMessageAck.msg_id`: 16 bytes returned as
/// a 32-char lowercase hex string per contract §4.1.
const SERVER_MSG_ID_HEX_LEN: usize = 32;

/// Внутренний helper: routes facade-уровневое текстовое сообщение через
/// активный gateway connection. Если `core.gateway()` is `None` —
/// возвращает legacy stub `MessageId([0u8; 16])`, сохраняя
/// backwards-compat для test fixtures и facade integration tests, которые
/// не bootstrap'ят networking (см. `tests/facade_integration.rs` etc.).
///
/// Если `core.gateway()` is `Some` — отправляет
/// `ClientPayload::SendMessage { to_user_id: chat_id.bytes, ciphertext: text.bytes }`
/// через `GatewayConnection::send_envelope`, ждёт ответный envelope,
/// требует `ServerPayload::SendAck { msg_id }`, декодирует 32-char hex →
/// 16 байт → возвращает `MessageId`. Server-side errors маршрутизируются
/// в `ClientError::Network` с диагностическим кодом.
///
/// ## Session-3 ограничения (полностью out-of-scope)
///
/// - **MLS AEAD encryption**: ciphertext в session 3 — placeholder
///   `text.into_bytes()`. Реальный MLS encrypt появится в session 5
///   (create_group + add_member) когда `UmbrellaGroup` будет wired в
///   facade. Mock gateway accept'ит любые байты — wire round-trip
///   exercise валидный.
/// - **Length-hiding padding** (umbrella_padding bucket selection):
///   защищает от traffic-analysis side-channel; layer вставится в
///   session 5+ как фильтр между MLS encrypt и transport send.
/// - **Cloud-wrap (для CloudChat)**: 3-of-5 Sealed Server message-key
///   wrap. Session 6 deliverable per pipeline plan.
/// - **Sealed-sender (для SecretChat)**: anonymous credential envelope.
///   Session 7 deliverable.
/// - **to_user_id маршрутизация**: session 3 использует `chat_id.0` как
///   to_user_id placeholder. Production должен map'ить chat_id →
///   recipient peer_id(s) через group membership. Wired в session 5+
///   когда group state существует.
///
/// Все ограничения tracked в `docs/audits/phd-b-pass5-remediation-2026-05-19.md`
/// F-CLIENT-FACADE-1 milestone closure roadmap.
///
/// Internal helper: routes a facade-level text message through the active
/// gateway connection. If `core.gateway()` is `None`, returns the legacy
/// stub `MessageId([0u8; 16])` for backwards-compat with tests that do not
/// bootstrap networking. When `Some`, sends
/// `ClientPayload::SendMessage` and decodes the server's
/// `SendMessageAck.msg_id` (32-char hex → 16 bytes) into `MessageId`.
///
/// Session-3 placeholders (out-of-scope for this session, tracked under
/// F-CLIENT-FACADE-1 roadmap): MLS AEAD encrypt (ciphertext is raw text
/// bytes), length-hiding padding, Cloud-wrap, sealed-sender,
/// chat_id → peer_id routing.
///
/// [`CloudChat`]: crate::facade::CloudChat
/// [`SecretChat`]: crate::facade::SecretChat
pub(crate) async fn send_mls_text(
    core: &Arc<ClientCore>,
    chat_id: ChatId,
    text: String,
) -> Result<MessageId> {
    let Some(gateway) = core.gateway().await else {
        // Legacy / Block-7.2 facade test fixtures path — no networking
        // wired. Keep the historical stub return so existing integration
        // tests (facade_integration.rs etc.) stay green until they are
        // updated to bootstrap a mock gateway.
        return Ok(MessageId([0u8; 16]));
    };

    let payload = ClientPayload::SendMessage {
        to_user_id: chat_id.0.to_vec(),
        ciphertext: text.into_bytes(),
    };
    gateway.send_envelope(payload).await.map_err(|e| {
        ClientError::Network(format!("send_envelope: {e}"))
    })?;
    let frame = gateway.recv_envelope().await.map_err(|e| {
        ClientError::Network(format!("recv_envelope: {e}"))
    })?;
    match frame.payload {
        ServerPayload::SendAck { msg_id } => decode_server_msg_id(&msg_id),
        ServerPayload::Error { code } => Err(ClientError::Network(format!(
            "gateway rejected SendMessage with code: {code}"
        ))),
        other => Err(ClientError::Network(format!(
            "expected SendAck after SendMessage, got: {other:?}"
        ))),
    }
}

/// Decode `SendMessageAck.msg_id` (32-char lowercase hex) into a
/// [`MessageId`] (16 bytes). Production gateway-svc always emits 16 bytes
/// hex per `rust_1mlrd/proto/umbrellax/gateway/v1/ws.proto:60` and the
/// in-process mock at `tests/mock_gateway/mod.rs` mirrors that shape via
/// `format!("{:032x}", seq)`.
///
/// Decode `SendMessageAck.msg_id` (32-char hex) into a `MessageId`.
fn decode_server_msg_id(hex_str: &str) -> Result<MessageId> {
    if hex_str.len() != SERVER_MSG_ID_HEX_LEN {
        return Err(ClientError::Network(format!(
            "gateway returned SendMessageAck.msg_id of length {} (expected {})",
            hex_str.len(),
            SERVER_MSG_ID_HEX_LEN
        )));
    }
    let bytes = hex::decode(hex_str).map_err(|e| {
        ClientError::Network(format!("gateway SendMessageAck.msg_id is not hex: {e}"))
    })?;
    let arr: [u8; 16] = bytes.try_into().map_err(|v: Vec<u8>| {
        ClientError::Network(format!(
            "gateway SendMessageAck.msg_id decoded to {} bytes (expected 16)",
            v.len()
        ))
    })?;
    Ok(MessageId(arr))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decrypted_message_debug_redacts_plaintext() {
        let msg = DecryptedMessage {
            message_id: MessageId([1u8; 16]),
            chat_id: ChatId([2u8; 32]),
            sender: PeerId([3u8; 32]),
            timestamp: 1_700_000_000_000,
            text: "private-chat-secret".to_string(),
        };

        let debug = format!("{msg:?}");

        assert!(
            !debug.contains("private-chat-secret"),
            "Debug output must not leak decrypted chat plaintext: {debug}"
        );
        assert!(
            debug.contains("text_len"),
            "Debug output should keep text length metadata for diagnostics: {debug}"
        );
    }
}
