//! Kotlin/Android FFI binding — `cdylib` + `rlib` crate для сборки AAR
//! через `cargo-ndk` + `uniffi-bindgen-kotlin`. Реальные FFI типы и
//! функции живут в [`umbrella_ffi`] — этот крейт re-export'ирует публичные
//! Rust-типы и re-export'ирует UniFFI scaffolding symbols из [`umbrella_ffi`].
//!
//! # Сборка
//!
//! Cargo targets:
//!
//! - `cdylib` → `libumbrella_ffi_kotlin.so` — загружается Android'ом
//!   через `System.loadLibrary("umbrella_ffi_kotlin")` (JNA feature
//!   uniffi Kotlin runtime'а).
//! - `rlib` — требуется чтобы `[[bin]]` `uniffi-bindgen-kotlin` мог
//!   `use umbrella_ffi_kotlin` для re-exports.
//!
//! Kotlin binding генерируется через
//! `cargo run --bin uniffi-bindgen-kotlin -- generate --library <.so> \
//! --language kotlin --out-dir ...` в `build-aar.sh`. Kotlin package
//! `uniffi.umbrella_ffi.*` (namespace совпадает).
//!
//! Kotlin/Android FFI binding — `cdylib` + `rlib` crate for building the
//! AAR via `cargo-ndk` + `uniffi-bindgen-kotlin`. Real FFI types and
//! functions live in [`umbrella_ffi`] — this crate re-exports the public
//! Rust types and re-exports UniFFI scaffolding symbols from [`umbrella_ffi`].
//!
//! # Build
//!
//! Cargo targets:
//!
//! - `cdylib` → `libumbrella_ffi_kotlin.so` — loaded by Android via
//!   `System.loadLibrary("umbrella_ffi_kotlin")` (JNA feature of the
//!   uniffi Kotlin runtime).
//! - `rlib` — required so the `uniffi-bindgen-kotlin` `[[bin]]` can
//!   `use umbrella_ffi_kotlin` for re-exports.
//!
//! The Kotlin binding is generated via `cargo run --bin
//! uniffi-bindgen-kotlin -- generate --library <.so> --language kotlin
//! --out-dir ...` inside `build-aar.sh`. Kotlin package
//! `uniffi.umbrella_ffi.*` (namespace matches).

#![warn(missing_docs)]

pub use umbrella_ffi::*;

/// Маркер сборки — обновляется при мажорном изменении Kotlin binding surface.
///
/// Build marker — updated on major Kotlin binding surface changes.
pub const BUILD_MARKER: &str = "umbrella-ffi-kotlin stage-7.9 aar";

// Re-export scaffolding symbols generated by umbrella-ffi. Creating a second
// namespace in this wrapper makes bindgen see metadata items for crate
// `umbrella_ffi` without a matching namespace group.
umbrella_ffi::uniffi_reexport_scaffolding!();
